import type { Book } from '../types/booktype';

export const MOCK_BOOKS: Book[] = [
  {
    id: '1',
    title: "Steve Jobs",
    author: "Walter Isaacson",
    genre: "Biography",
    price: 28.00,
    rentPrice: 3.50,
    rating: 4.8,
    cover: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=800",
    description: "The definitive biography of the man who obsessively combined technology and design.",
    content: "CHAPTER ONE: The childhood of a visionary. Precision was not a goal; it was the starting point.",
    bgColor: "bg-[#f2f2f2]"
  },
  {
    id: '2',
    title: "Creative Selection",
    author: "Ken Kocienda",
    genre: "Tech",
    price: 32.00,
    rentPrice: 4.50,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&q=80&w=800",
    description: "Inside Apple's design process during the golden age of Steve Jobs.",
    content: "The demos were high-stakes. We weren't just building software; we were building an experience.",
    bgColor: "bg-[#f1f5f9]"
  },
  {
    id: '3',
    title: "Minimalism",
    author: "Kyle Chayka",
    genre: "Design",
    price: 22.50,
    rentPrice: 4.00,
    rating: 4.7,
    cover: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=800",
    description: "A look into how the radical art movement became a digital lifestyle.",
    content: "Less is only more when the 'less' is intentional and perfect in form.",
    bgColor: "bg-[#fafafa]"
  },
  {
    id: '4',
    title: "Zero to One",
    author: "Peter Thiel",
    genre: "Tech",
    price: 26.00,
    rentPrice: 3.99,
    rating: 4.6,
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
    description: "Notes on startups, or how to build the future of technology.",
    content: "Every moment in business happens only once.",
    bgColor: "bg-[#e2e8f0]"
  },
  {
    id: '5',
    title: "Meditations",
    author: "Marcus Aurelius",
    genre: "Philosophy",
    price: 15.00,
    rentPrice: 1.99,
    rating: 5.0,
    cover: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?auto=format&fit=crop&q=80&w=800",
    description: "Timeless stoic wisdom from the Roman Emperor.",
    content: "The happiness of your life depends upon the quality of your thoughts.",
    bgColor: "bg-[#eceae2]"
  },
  {
    id: '6',
    title: "The Daily Stoic",
    author: "Ryan Holiday",
    genre: "Philosophy",
    price: 18.50,
    rentPrice: 2.50,
    rating: 4.8,
    cover: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?auto=format&fit=crop&q=80&w=800",
    description: "366 days of Stoic insights for a better life.",
    content: "Control what you can. Release what you cannot.",
    bgColor: "bg-[#f5e9da]"
  },
  {
    id: '7',
    title: "Sapiens",
    author: "Yuval Noah Harari",
    genre: "History",
    price: 30.00,
    rentPrice: 4.99,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1585862705417-660da3873a0c?auto=format&fit=crop&q=80&w=800",
    description: "A brief history of humankind.",
    content: "History is something very few people have been doing while everyone else was ploughing fields.",
    bgColor: "bg-[#f4e7e4]"
  },
  {
    id: '8',
    title: "Brief Answers",
    author: "Stephen Hawking",
    genre: "Science",
    price: 24.00,
    rentPrice: 3.50,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=800",
    description: "Final thoughts on the universe's biggest questions.",
    content: "Remember to look up at the stars and not down at your feet.",
    bgColor: "bg-[#e8ebf1]"
  },
  {
    id: '9',
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Productivity",
    price: 21.00,
    rentPrice: 2.99,
    rating: 4.7,
    cover: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&q=80&w=800",
    description: "Rules for success in a distracted digital world.",
    content: "Deep work is the ability to focus without distraction.",
    bgColor: "bg-[#eff6f1]"
  },
  {
    id: '10',
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Productivity",
    price: 25.00,
    rentPrice: 3.99,
    rating: 5.0,
    cover: "https://images.unsplash.com/photo-1589998059171-988d887df646?auto=format&fit=crop&q=80&w=800",
    description: "Build good habits and break bad ones.",
    content: "Every action you take is a vote for the person you wish to become.",
    bgColor: "bg-[#ebf4ff]"
  },
  {
    id: '11',
    title: "Shoe Dog",
    author: "Phil Knight",
    genre: "Biography",
    price: 22.00,
    rentPrice: 3.00,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=800",
    description: "The inside story of the Nike company's early days.",
    content: "Don't tell people how to do things, tell them what to do.",
    bgColor: "bg-[#fff1f0]"
  },
  {
    id: '12',
    title: "Dune",
    author: "Frank Herbert",
    genre: "Sci-Fi",
    price: 19.50,
    rentPrice: 2.99,
    rating: 4.8,
    cover: "https://images.unsplash.com/photo-1533319417894-6f8c69c1815f?auto=format&fit=crop&q=80&w=800",
    description: "Story of power on the desert planet Arrakis.",
    content: "I must not fear. Fear is the mind-killer.",
    bgColor: "bg-[#fdf2e2]"
  },
  {
    id: '13',
    title: "1984",
    author: "George Orwell",
    genre: "Fiction",
    price: 14.00,
    rentPrice: 1.50,
    rating: 4.7,
    cover: "https://images.unsplash.com/photo-1543004218-29471b54b055?auto=format&fit=crop&q=80&w=800",
    description: "Prophecy about the future of surveillance.",
    content: "Big Brother is watching you.",
    bgColor: "bg-[#f5f5f5]"
  },
  {
    id: '14',
    title: "Foundation",
    author: "Isaac Asimov",
    genre: "Sci-Fi",
    price: 23.00,
    rentPrice: 3.50,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1614850523296-d8c1af93d400?auto=format&fit=crop&q=80&w=800",
    description: "Fall of a galactic empire.",
    content: "Violence is the last refuge of the incompetent.",
    bgColor: "bg-[#f0f2ff]"
  },
  {
    id: '15',
    title: "Grit",
    author: "Angela Duckworth",
    genre: "Psychology",
    price: 21.50,
    rentPrice: 3.20,
    rating: 4.8,
    cover: "https://images.unsplash.com/photo-1474366521946-c3d4b507ad0a?auto=format&fit=crop&q=80&w=800",
    description: "Resilience is the secret to success.",
    content: "Our vanity promotes the culture of genius.",
    bgColor: "bg-[#faf3f2]"
  },
  {
    id: '16',
    title: "Essentialism",
    author: "Greg McKeown",
    genre: "Psychology",
    price: 20.00,
    rentPrice: 2.80,
    rating: 4.7,
    cover: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=800",
    description: "The disciplined pursuit of less.",
    content: "If you don't prioritize your life, someone else will.",
    bgColor: "bg-[#ffffff]"
  },
  {
    id: '17',
    title: "Thinking Fast",
    author: "Daniel Kahneman",
    genre: "Psychology",
    price: 27.00,
    rentPrice: 4.50,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&q=80&w=800",
    description: "Two systems drive the way we think.",
    content: "Intelligence is the ability to find relevant material.",
    bgColor: "bg-[#f0f9ff]"
  },
  {
    id: '18',
    title: "Grid Systems",
    author: "Josef Müller-Brockmann",
    genre: "Design",
    price: 45.00,
    rentPrice: 7.00,
    rating: 5.0,
    cover: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&q=80&w=800",
    description: "The bible of typography for professional designers.",
    content: "The grid system is an aid, not a guarantee.",
    bgColor: "bg-[#f5f5f7]"
  },
  {
    id: '19',
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Fiction",
    price: 16.00,
    rentPrice: 2.00,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=800",
    description: "Listen to your heart.",
    content: "When you want something, the universe conspires.",
    bgColor: "bg-[#fffbf0]"
  },
  {
    id: '20',
    title: "Architecture",
    author: "Zaha Hadid",
    genre: "Design",
    price: 55.00,
    rentPrice: 9.00,
    rating: 5.0,
    cover: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&q=80&w=800",
    description: "Legacy of Hadid's architectural forms.",
    content: "Architecture must provide a world that didn't exist before.",
    bgColor: "bg-[#f2f4f6]"
  },
  {
    id: '21',
    title: "Grit 2.0",
    author: "Angela Duckworth",
    genre: "Psychology",
    price: 21.50,
    rentPrice: 3.20,
    rating: 4.8,
    cover: "https://images.unsplash.com/photo-1526336024174-e58f5cdd8e13?auto=format&fit=crop&q=80&w=800",
    description: "Strategies for perseverance.",
    content: "Endurance is rare.",
    bgColor: "bg-[#f9f2f8]"
  },
  {
    id: '22',
    title: "Creative Inc.",
    author: "Ed Catmull",
    genre: "Business",
    price: 29.00,
    rentPrice: 4.50,
    rating: 4.9,
    cover: "https://images.unsplash.com/photo-1541844053589-3d5b90220032?auto=format&fit=crop&q=80&w=800",
    description: "Leadership from the founder of Pixar.",
    content: "Failure isn't a necessary evil.",
    bgColor: "bg-[#f0f7ff]"
  }
];